name: Preview Deployment to Cloudflare Pages
on:
  push:
    branches:
      - "!dev"
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Setup Document Dependencies
        run: |
          pip install -r ./docs/requirements.txt

      - name: Build with MKDocs
        run: |
          PYTHONPATH=src mkdocs build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: graia-ariadne-preview
          directory: site
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
