name: Publish to PyPI
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.**"
      - "dev-**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: 1.1.11

      - name: Setup Poetry Dependencies
        run: |
          poetry install --no-dev

      - name: Poetry build
        run: |
          poetry build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: dist/

      - name: Poetry Publish
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry publish
